global:
  scrape_interval:     30s
  evaluation_interval: 1m
  external_labels:
    monitor: 'ptvn-prom'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "{IP}:9093"

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
      port: 9090
    static_configs:
      - targets: ['{IP}:9090']