global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job', 'projects', 'group', 'instance']
  receiver: 'line-noti'
  group_interval: 30s
  group_wait: 45s
  repeat_interval: 3h

receivers:
- name: 'line-noti'
  webhook_configs:
  - url: '{IP}/webhook'
    send_resolved: true
    http_config:
      bearer_token: 's4XZKAW2k0sDzgcctusZ7PvIbkEIofTSDDcTTx6JTIS'